services:
  app:
    build:
#      context: docker
      dockerfile: docker/app/Dockerfile
    ports:
      - "8081:8080" # Экспонируем порт приложения
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=your_password
      - DB_NAME=buildings_db
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14
    container_name: buildings_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: buildings_db
    ports:
      - "5432:5432" # Экспонируем порт PostgreSQL
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: