#host: ${DB_HOST}
#port: ${DB_PORT}
#user: ${DB_USER}
#password: ${DB_PASSWORD}
#db: ${DB_NAME}

host: db  # для докер контейнера golang
#host: localhost #для работы с локально гошкой
port: 5432
user: postgres
password: your_password
db: buildings_db